---
##title: "Nba players analysis"
##author: "Przemek Szafert"
##date: "8/22/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE)

```

```{r data import, include=FALSE}

library("tidyverse")
library("knitr")
library(plotly)

player <- read.csv("../data_raw/datasets_1358_30676_Players.csv") %>%
  select(-1,)
playerData <- read_csv("../data_raw/datasets_1358_30676_player_data.csv")
Seasons_stats <- read_csv("../data_raw/Seasons_Stats.csv")%>%
    filter(Year > 1985)

```

## Short dataset description

Three datasets are used:

1. **`Players`**  contains 3922 observations of 7 variables. 

1. **`player_data`** contains 4550 observations of 8 variables. 

1. **`Seasons_Stats`** contains 24691 observations of 53 variables. 



## General Statistics

### Points per game

```{r Points-per-game}

Ppg <- Seasons_stats %>%
  group_by(Player)%>%
  summarise(sum.PTS = sum(PTS), sum.G = sum(G))%>%
  mutate(avg.PTSperG = sum.PTS/sum.G) %>%
  #ungroup()%>%
  select(Player,sum.PTS, sum.G,avg.PTSperG)%>%
  arrange(desc(avg.PTSperG))


p <- ggplot(Ppg, aes (
        x = sum.G, 
        y = avg.PTSperG,
        color = Player,
        shape = ifelse(Player == 'Michael Jordan*', 'TRUE', 'FALSE')
        #size = avg.PTSperG
        )) +
        geom_point(aes (alpha = 1 / 10)) +
        scale_shape_manual(guide = F, values = c(18,15))+
        theme(legend.position = "none")

fig <- ggplotly(p)
fig

```
